"""
Data structures for representing trajectory trees in Tree GRPO.
"""
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from tinker_cookbook.rl.types import Trajectory


@dataclass
class TreeNode:
    """
    A node in the trajectory tree.

    Each node represents a complete trajectory that may have been branched from
    a parent trajectory at a specific token position.
    """

    trajectory: Trajectory
    """The complete trajectory for this node"""

    node_id: int
    """Unique identifier for this node"""

    parent_id: int | None = None
    """ID of parent node (None for root nodes)"""

    branch_transition_idx: int | None = None
    """Index of the transition where branching occurred (which assistant message)"""

    branch_token_idx: int | None = None
    """Token position within the transition's action where branch occurred"""

    depth: int = 0
    """Depth in the tree (0 for roots)"""

    is_leaf: bool = True
    """Whether this node is a leaf (has no children)"""

    children_ids: list[int] = field(default_factory=list)
    """List of child node IDs"""

    final_reward: float = 0.0
    """Final reward for this trajectory"""

    def get_total_tokens(self) -> int:
        """Get total number of tokens in this trajectory."""
        return sum(len(t.ac.tokens) for t in self.trajectory.transitions)

    def get_token_sequence(self) -> list[int]:
        """
        Get the complete token sequence for this trajectory.
        Concatenates all action tokens from all transitions.
        """
        tokens = []
        for transition in self.trajectory.transitions:
            tokens.extend(transition.ac.tokens)
        return tokens

    def get_token_prefix_up_to(self, transition_idx: int, token_idx: int) -> list[int]:
        """
        Get token prefix up to (but not including) the specified position.

        Args:
            transition_idx: Index of the transition
            token_idx: Token position within that transition

        Returns:
            List of all tokens before the branch point
        """
        prefix = []
        for i, transition in enumerate(self.trajectory.transitions):
            if i < transition_idx:
                prefix.extend(transition.ac.tokens)
            elif i == transition_idx:
                prefix.extend(transition.ac.tokens[:token_idx])
                break
        return prefix


class TrajectoryTree:
    """
    A tree of trajectories for Tree GRPO.

    The tree starts with M root nodes (independent trajectories) and grows by
    branching at random token positions within assistant messages. Each branch
    creates K-1 alternative continuations generated by Gemini.
    """

    def __init__(self):
        self.nodes: dict[int, TreeNode] = {}
        """All nodes indexed by node ID"""

        self.root_ids: list[int] = []
        """IDs of root nodes"""

        self.leaf_ids: list[int] = []
        """IDs of leaf nodes (updated as tree grows)"""

        self._next_id: int = 0
        """Counter for generating unique node IDs"""

    def add_root(self, trajectory: Trajectory, final_reward: float) -> int:
        """
        Add a root trajectory to the tree.

        Args:
            trajectory: The root trajectory
            final_reward: Final reward for this trajectory

        Returns:
            node_id: The ID of the created node
        """
        node_id = self._next_id
        self._next_id += 1

        node = TreeNode(
            trajectory=trajectory,
            node_id=node_id,
            parent_id=None,
            depth=0,
            is_leaf=True,
            final_reward=final_reward,
        )

        self.nodes[node_id] = node
        self.root_ids.append(node_id)
        self.leaf_ids.append(node_id)

        return node_id

    def add_child(
        self,
        parent_id: int,
        trajectory: Trajectory,
        final_reward: float,
        branch_transition_idx: int,
        branch_token_idx: int,
    ) -> int:
        """
        Add a child trajectory that branched from a parent.

        Args:
            parent_id: ID of the parent node
            trajectory: The child trajectory
            final_reward: Final reward for this trajectory
            branch_transition_idx: Which transition (assistant message) was branched
            branch_token_idx: Token position where branch occurred

        Returns:
            node_id: The ID of the created node
        """
        if parent_id not in self.nodes:
            raise ValueError(f"Parent node {parent_id} not found in tree")

        parent = self.nodes[parent_id]

        node_id = self._next_id
        self._next_id += 1

        node = TreeNode(
            trajectory=trajectory,
            node_id=node_id,
            parent_id=parent_id,
            branch_transition_idx=branch_transition_idx,
            branch_token_idx=branch_token_idx,
            depth=parent.depth + 1,
            is_leaf=True,
            final_reward=final_reward,
        )

        self.nodes[node_id] = node

        # Update parent
        parent.children_ids.append(node_id)
        if parent.is_leaf:
            parent.is_leaf = False
            self.leaf_ids.remove(parent_id)

        # Add to leaves
        self.leaf_ids.append(node_id)

        return node_id

    def get_leaves(self) -> list[TreeNode]:
        """Get all leaf nodes."""
        return [self.nodes[leaf_id] for leaf_id in self.leaf_ids]

    def get_nodes_at_depth(self, depth: int) -> list[TreeNode]:
        """Get all nodes at a specific depth."""
        return [node for node in self.nodes.values() if node.depth == depth]

    def get_branchable_leaves(self, max_depth: int) -> list[TreeNode]:
        """
        Get all leaf nodes that can still be branched (depth < max_depth).

        Args:
            max_depth: Maximum allowed depth

        Returns:
            List of leaf nodes with depth < max_depth
        """
        return [node for node in self.get_leaves() if node.depth < max_depth]

    def get_statistics(self) -> dict[str, Any]:
        """Get tree statistics for logging."""
        depths = [node.depth for node in self.nodes.values()]
        num_children = [len(node.children_ids) for node in self.nodes.values() if not node.is_leaf]

        return {
            "total_nodes": len(self.nodes),
            "root_nodes": len(self.root_ids),
            "leaf_nodes": len(self.leaf_ids),
            "max_depth": max(depths) if depths else 0,
            "avg_depth": sum(depths) / len(depths) if depths else 0,
            "avg_branching_factor": sum(num_children) / len(num_children) if num_children else 0,
        }

    def find_nodes_with_prefix(self, prefix: list[int]) -> list[int]:
        """
        Find all node IDs whose token sequences start with the given prefix.

        Args:
            prefix: Token sequence prefix to match

        Returns:
            List of node IDs with matching prefix
        """
        matching_ids = []
        prefix_len = len(prefix)

        for node_id, node in self.nodes.items():
            node_tokens = node.get_token_sequence()
            if len(node_tokens) >= prefix_len and node_tokens[:prefix_len] == prefix:
                matching_ids.append(node_id)

        return matching_ids

    def serialize_to_graph(self) -> dict[str, Any]:
        """
        Serialize tree to a graph structure for visualization/storage.

        Returns:
            Dictionary with nodes and edges in NetworkX-compatible format
        """
        nodes_data = []
        edges_data = []

        for node_id, node in self.nodes.items():
            nodes_data.append({
                "id": node_id,
                "depth": node.depth,
                "is_leaf": node.is_leaf,
                "is_root": node.parent_id is None,
                "final_reward": node.final_reward,
                "num_transitions": len(node.trajectory.transitions),
                "total_tokens": node.get_total_tokens(),
            })

            if node.parent_id is not None:
                edges_data.append({
                    "source": node.parent_id,
                    "target": node_id,
                    "branch_transition_idx": node.branch_transition_idx,
                    "branch_token_idx": node.branch_token_idx,
                })

        return {
            "nodes": nodes_data,
            "edges": edges_data,
            "statistics": self.get_statistics(),
        }

    def save_to_file(self, filepath: str | Path):
        """
        Save tree to a JSON file.

        Args:
            filepath: Path to save the tree JSON
        """
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        graph_data = self.serialize_to_graph()

        with open(filepath, 'w') as f:
            json.dump(graph_data, f, indent=2)
